config/routes.rb
Rails.application.routes.draw do
  get 'reports/export'

  resources :groups, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'
  root to: 'home#index'
  resources :users do 
    member do 
      get :report
      get :history
    end
  end
  resources :locations, only: [:index, :create] do
    post :queue, on: :collection
  end
  resources :check_ins, only: [:index, :create] do
    post :queue, on: :collection
  end
  resources :check_outs, only: [:index, :create] do
    post :queue, on: :collection
  end
  post 'authenticate', to: 'authentication#authenticate'
  post 'refresh_token', to: 'authentication#refresh_token'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/current_info', to: 'profile#current_info'
  get '/history_info', to: 'profile#history_info'

  resources :groups, only: [:index, :create, :update]
  resources :reports, only: [:index] do
    collection do
      get :details
      get :detail
      get :get_general, to: 'reports#get_general'
      get :general
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :at, -> (date) { where("date_trunc('day', created_at) = ?", date) }
end

app/models/check_in_day_view.rb
class CheckInDayView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_in_day_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/check_in_late_view.rb
class CheckInLateView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_in_late_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/check_out.rb
class CheckOut < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :at, -> (date) { where("date_trunc('day', created_at) = ?", date) }
end

app/models/check_out_day_view.rb
class CheckOutDayView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_out_day_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/check_out_early_view.rb
class CheckOutEarlyView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_out_early_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/day_month.rb
class DayMonth < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups

  validates :name, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :date, -> (from_date, to_date) { where('created_at BETWEEN ? AND ?', from_date.beginning_of_day, to_date.end_of_day) }
end

app/models/report.rb
class Report
  def self.refresh
    CheckInDayView.refresh
    CheckInLateView.refresh
    CheckOutDayView.refresh
    CheckOutEarlyView.refresh
    HistoryCheckInOutView.refresh
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address
  has_many :check_ins
  has_many :check_outs
  has_many :locations
  has_many :user_groups
  has_many :groups, through: :user_groups

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :not_admin, -> { where.not(admin: true) }
  scope :admin,     -> { where(admin: true) }
  scope :online,    -> { where(online_status: true) }
  scope :offline,   -> { where(online_status: false) }
  scope :search,    ->  (query) { where("name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%") }

  def info
    "#{name} - #{latest_update_time}"
  end

  def latest_update_time
    update_location_at.strftime("%d/%m/%Y %H:%M")
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
  	   authorize_admin! 
       load_data
       @home_page = true
       @groups = Group.all
    end
  end

  private

  def load_data
    @positions ||= pluck(decorate(users), :id, :latitude, :longitude, :info, :icon_path, :title)
    @center ||= Geocoder::Calculations.geographic_center users.pluck(:latitude, :longitude)
    @users ||= Kaminari.paginate_array(check_ins).page(params[:page]).per(10)
    @online ||= users.online.count
    @offline ||= users.offline.count
  end

  def check_ins
    @check_ins ||= Api::V1::HistoryCheckInOutQuery.new(params).render
  end

  def check_ins_ids
    check_ins.map { |item| item[:user_id] }
  end

  def users
    User.where(id: check_ins_ids)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authorize_admin!

  def details
    @users = User.not_admin.page(params[:page]).per(10)
  end

  def get_general
  	
  end

  def general
    @check_ins = Api::V1::CheckInsQuery.new(month: params[:month]).render.group_by { |x| x[:group_name] }
    @check_outs = Api::V1::CheckOutsQuery.new(month: params[:month]).render.group_by { |x| x[:group_name] }
    @late_check_ins = Api::V1::LateCheckInsQuery.new(month: params[:month]).render.group_by { |x| x[:group_name] }
    @early_check_outs = Api::V1::EarlyCheckOutsQuery.new(month: params[:month]).render.group_by { |x| x[:group_name] }
    @time_of_day = Api::V1::TimeOfDayQuery.new(month: params[:month]).render.group_by { |x| x[:group_name] }
    res = {}
    Group.pluck(:name).each do |group_name|
      gs = group_name
      res[gs] ||= {}
      if @check_ins && @check_ins[gs]
        @check_ins[gs].each do |v|
          res[gs][:check_in] ||= []
          res[gs][:check_in] << v
        end
      end
      if @check_outs && @check_outs[gs]
        @check_outs[gs].each do |v|
          res[gs][:check_out] ||= []
          res[gs][:check_out] << v
        end
      end
      if @late_check_ins && @late_check_ins[gs]
        @late_check_ins[gs].each do |v|
          res[gs][:late_check_in] ||= []
          res[gs][:late_check_in] << v
        end
      end
      if @early_check_outs && @early_check_outs[gs]
        @early_check_outs[gs].each do |v|
          res[gs][:early_check_out] ||= []
          res[gs][:early_check_out] << v
        end
      end
      if @time_of_day && @time_of_day[gs]
        @time_of_day[gs].each do |v|
          res[gs][:time_of_day] ||= []
          res[gs][:time_of_day] << v
        end
      end
    end
    @result = res
  end

  def detail
    @user = User.find_by(id: params[:id])
    @from_date = params[:from_date]
    @to_date = params[:to_date]
    @reports = Api::V1::DetailReportQuery.new(params).render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emojis_helper.rb
module EmojisHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_check_ins.html.erb
<%= users.as_json %>
<% users.each do |key, val| %>
<table class="table table-bordered">
  <thead  bgcolor='#026c48'>
    <td align="center"><font color="#fff">STT</font></td>
    <td align="center"><font color="#fff">Nhân viên</font></td>
    <% (1..31).each do |day| %>
      <td align="center"><font color="#fff"><%= "#{day.to_s}" %></font></td>
    <% end %>
  </thead>
  <tbody>
    <% val.each_with_index do |user, index| %>
      <tr>
        <td align="center"><%= (index+1).to_s %></td>
        <td><%= user[:name] %></td>
        <% (1..31).each do |day| %>
          <td><%= user["day#{day}".to_sym] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/reports/_date_filter.html.erb
<div class="well">
  <div class="row">  
    <div class="col-md-3">
      Báo cáo:<br/>
    </div>
    <div class="col-md-5">
      <div class="row">      
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-5"><label style="padding-top: 6px;" for="from_date">Từ:</label></div>
              <div class="col-md-7">
                <input data-date-format="dd/mm/yyyy" class="form-control" id="from_date" type="text" data-provide='datepicker' name="from_date" value="<%= params[:from_date].present? ? params[:from_date] : Date.current.strftime("%d/%m/%Y") %>" >
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-5">
                <label style="padding-top: 6px;" for="to_date">Đến:</label>
              </div>
              <div class="col-md-7">
                <input data-date-format="dd/mm/yyyy" class="form-control" id="to_date" type="text" data-provide='datepicker' name="to_date" value="<%= params[:to_date].present? ? params[:to_date] : Date.current.strftime("%d/%m/%Y") %>" >
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_info.html.erb
<table class="table table-bordered">
  <col width="5%">
  <col width="30%">
  <col width="30%">
  <col width="15%">
  <col width="15%">
  <col width="5%">
  <thead  bgcolor='#026c48'>
    <td align="center"><font color="#fff">STT</font></td>
    <td align="center"><font color="#fff">User</font></td>
    <td align="center"><font color="#fff">Check In</font></td>
    <td align="center"><font color="#fff">Check Out</font></td>
    <td align="center"><font color="#fff">Sớm</font></td>
    <td align="center"><font color="#fff">Trễ</font></td>
  </thead>
  <tbody>
    <% users.each_with_index do |user, index| %>
        <tr>
          <td align="center"><%= (index+1).to_s %></td>
          <td><%= user[:user_id] %></td>
          <td><%= user[:check_in_date].to_s + " " + user[:check_in_time].to_s %></td>
          <td><%= user[:check_out_date].to_s + " " + user[:check_out_time].to_s %></td>
          <td><%= user[:early] %></td>
          <td><%= user[:late] %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= paginate users, :theme => 'twitter-bootstrap-3' %>

app/views/reports/_list.html.erb
<table class="table table-bordered">
<col width="5%">
<col width="30%">
<col width="30%">
<col width="30%">
<col width="5%">
<thead  bgcolor='#026c48'>
  <td align="center"><font color="#fff">STT</font></td>
  <td align="center"><font color="#fff">Nhân viên</font></td>
  <td align="center"><font color="#fff">Email</font></td>
  <td align="center"><font color="#fff">Nhóm</font></td>
  <td align="center"><font color="#fff">Xuất báo cáo</font></td>
</thead>
<tbody>
  <% users.each_with_index do |user, index| %>
      <tr id="user-<%= user.id %>">
        <input type="hidden" name="id" value="<%= user.id %>">
        <td align="center"><%= (index+1).to_s %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= render partial: "users/groups", locals: { groups: user.groups } %></td>
        <td align="center">
          <input type="submit" value="Xuất báo cáo", class="btn btn-default">
        </td>
      </tr>
  <% end %>
</tbody>
</table>
<%= paginate users, :theme => 'twitter-bootstrap-3' %>

app/views/reports/_month_filter.html.erb
<div class="well">
  <div class="row">  
    <div class="col-md-3">
      Báo cáo:<br/>
    </div>
    <div class="col-md-9">
      <div class="row">      
        <%= form_tag(general_reports_path(format: :xlsx), method: :get) do %>
          <div class="col-md-5"><label style="padding-top: 6px;" for="month">Chọn tháng:</label></div>
          <div class="col-md-4">
            <select name="month" class="form-control">
              <% (1..12).each do |month| %>
              <option value="<%= month %>" selected="<%= params[:month].present? ? params[:month] : Date.current.month %>"><%= month.to_s %></option>
              <% end %>
            </select>
          </div>
          <div class="col-md-3">
            <input type="submit" value="Xuất báo cáo" class="btn btn-primary"/>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reports/details.html.erb
<h1>Chọn báo cáo</h1>
<%= form_tag(detail_reports_path(format: :xls), method: :get) do %>
  <%= render "reports/date_filter" %>
  <%= render partial: "reports/list", locals: { users: @users } %>
<% end %>

app/views/reports/general.html.erb
<%= render "reports/month_filter" %>
<%= @result.as_json %>

app/views/reports/get_general.html.erb
<%= render "reports/month_filter" %>

app/views/reports/index.html.erb
<h1>Chọn báo cáo</h1>
<%= form_tag(detail_reports_path(format: :xls), method: :get) do %>
  <%= render "reports/date_filter" %>
  <%= render partial: "reports/list", locals: { users: @users } %>
<% end %>