config/routes.rb
Rails.application.routes.draw do
  get 'reports/export'

  resources :groups, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'
  root to: 'home#index'
  resources :users do 
    member do 
      get :report
      get :history
    end
  end
  resources :locations, only: [:index, :create] do
    post :queue, on: :collection
  end
  resources :check_ins, only: [:index, :create] do
    post :queue, on: :collection
  end
  resources :check_outs, only: [:index, :create] do
    post :queue, on: :collection
  end
  post 'authenticate', to: 'authentication#authenticate'
  post 'refresh_token', to: 'authentication#refresh_token'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/current_info', to: 'profile#current_info'
  get '/history_info', to: 'profile#history_info'

  resources :groups, only: [:index, :create, :update]
  resources :reports, only: [:index] do
    collection do
      get :details
      get :detail
      get :get_general, to: 'reports#get_general'
      get :general
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :at, -> (date) { where("date_trunc('day', created_at) = ?", date) }
end

app/models/check_in_day_view.rb
class CheckInDayView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_in_day_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/check_in_late_view.rb
class CheckInLateView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_in_late_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/check_out.rb
class CheckOut < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :at, -> (date) { where("date_trunc('day', created_at) = ?", date) }
end

app/models/check_out_day_view.rb
class CheckOutDayView < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(:check_out_day_views, concurrently: true)
  end

  def readonly?
    true
  end
end

app/models/day_month.rb
class DayMonth < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups

  validates :name, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address

  validates :latitude, presence: true
  validates :longitude, presence: true

  scope :date, -> (from_date, to_date) { where('created_at BETWEEN ? AND ?', from_date.beginning_of_day, to_date.end_of_day) }
end

app/models/report.rb
class Report
  def self.refresh
    CheckInDayView.refresh
    CheckInLateView.refresh
    CheckOutDayView.refresh
    CheckOutEarlyView.refresh
    HistoryCheckInOutView.refresh
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  reverse_geocoded_by :latitude, :longitude
  after_validation :fetch_address
  has_many :check_ins
  has_many :check_outs
  has_many :locations
  has_many :user_groups
  has_many :groups, through: :user_groups

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :not_admin, -> { where.not(admin: true) }
  scope :admin,     -> { where(admin: true) }
  scope :online,    -> { where(online_status: true) }
  scope :offline,   -> { where(online_status: false) }
  scope :search,    ->  (query) { where("name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%") }

  def info
    "#{name} - #{latest_update_time}"
  end

  def latest_update_time
    update_location_at.strftime("%d/%m/%Y %H:%M")
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emojis_helper.rb
module EmojisHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
<% if @form_error && @form_error.errors.any? %>
	<ul>
	  <% @form_error.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	</ul>
<% end %>

app/views/layouts/_header.html.erb
<div class="header clearfix" style="margin-top:5px;">
    <nav>
      <ul class="nav nav-pills pull-right">  
        <li role="presentation">
          <%=link_to "Home", root_path %>
        </li>      
        <% if logged_in? %>
        	<% if admin? %>
		        <li role="presentation" class="<%= active_class('/users') %>">
		        	<%= link_to "Users", users_path %>
		        </li>
        	<% end %>
			<li role="presentation">
				<%=link_to "Log Out", logout_path %>
			</li>
		<% else %>
			<li role="presentation">
			<%= link_to "Log In", login_path %>
			</li>
		<% end %>
      </ul>
    </nav>
  </div>

app/views/layouts/_menu.html.erb
<ul class="nav nav-pills">
  <li role="presentation">
    <%= link_to "Trang chủ", root_path %>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Quản lý nhân viên <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li role="presentation">
        <%= link_to "Danh sách nhân viên", users_path %>
      </li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="/groups/new" role="button" aria-haspopup="true" aria-expanded="false">
      Quản lý nhóm <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li role="presentation">
        <%= link_to "Danh sách nhóm", groups_path %>
      </li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="/groups/new" role="button" aria-haspopup="true" aria-expanded="false">
        Báo cáo <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li role="presentation">
          <%= link_to "Báo cáo chi tiết", details_reports_path %>
        </li>
        <li role="presentation">
          <%= link_to "Báo cáo tổng hợp", get_general_reports_path %>
        </li>
      </ul>
  </li>
  <% if logged_in? %>
    <li role="presentation" class="dropdown pull-right">
      <%= link_to "Đăng xuất", logout_path, method: :delete %>
    </li>
  <% else %>
    <li role="presentation" class="dropdown pull-right">
    <%= link_to "Đăng nhập", login_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_toolbar.html.erb
<div class='col-md-3'>
<div id="imaginary_container"> 
    <%= form_tag(root_path, method: :get) do %>
      <div class="input-group stylish-input-group">
        <input type="text" class="form-control" name="query" placeholder="Tìm nhân viên" value=<%= params[:query] %> >
        <span class="input-group-addon">
            <button type="submit">
                <span class="glyphicon glyphicon-search"></span>
            </button>  
        </span>
      </div>
    <% end %>
</div>
</div>
<div class='col-md-6'>
<ul class="nav nav-pills">
  <li role="presentation" class="dropdown">
    <div class="dropdown">
      <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary" data-target="#" href="/page.html">
          Lọc theo nhóm <span class="caret"></span>
      </a>
      <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
        <li><a href="/">Chọn tất cả</a></li>
        <% @groups.each do |group| %>
          <li><a href="/?group_id=<%= group.id %>"><%= group.name %></a></li>
        <% end %>
      </ul>
    </div>
  </li>
</ul>
</div>
<div class='col-md-3'>
Online: <font color='green'><%= @online %></font>&nbsp;&nbsp;
Offline: <font color='red'><%= @offline %></font>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NTP-Phần mềm giám sát GPS</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDC_f7OaJMYMK92QjscI1B8Jo9U_33bBhQ&libraries=places" ></script>
    <%= action_cable_meta_tag %>
    <%= yield :css_include %>
    <style>
      #map {height: 50vh;}
      #map_detail {height: 80vh;}
    </style>
  </head>

  <body style="background-color: #FEFFFF;">
    <div class='container' style='padding-left: 0px; padding-right: 0px;'>
      <% if logged_in? %>
        <div class='row' style='margin-top: -2px; margin-bottom: -10px;'>
          <div class='col-md-8 col-md-offset-4'>
            <%= render 'layouts/menu' %>
          </div>
        </div>
      <% end %>
      </div>
      <div class='bannerimg' style='height: 75px; margin-top: 10px;'>        
      </div>
      <% if @home_page %>
        <div class='container'>      
        <%= render 'layouts/toolbar' %>
      </div>
      <% end %>
      <div class='container'>
      	<%= render 'layouts/flash' %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
      <br />
      <div class="copyright bgimg">
        <div class="container">
          <div class="col-md-6">
            <p>@ Copyrights 2006 by Tien Phong Plastic Joint-Stock company</p>
          </div>
          <div class="col-md-6">
            <ul class="bottom_ul">
              <li><a href="http://www.nhuatienphong.vn/pg-16593/san-pham?MenuID=9052">Sản phẩm</a></li>
              <li><a href="http://www.nhuatienphong.vn/pg-16594/bang-gia?MenuID=9053">Bảng giá</a></li>
              <li><a href="http://www.nhuatienphong.vn/pg-16595/hổ-trợ-khách-hàng?MenuID=9054">Hỗ trợ khách hàng</a></li>
              <li><a href="http://mail.nhuatienphong.vn:3000/">Email</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <%= yield :js_include %>    
  </body>
</html>